# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='entrenamiento',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Curso'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Piloto'),
        ),
        migrations.AddField(
            model_name='curso',
            name='entrenamientos',
            field=models.ManyToManyField(through='training.Entrenamiento', to='training.Piloto'),
        ),
    ]
