# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170922_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='vigencia',
            field=models.IntegerField(help_text='En meses.'),
        ),
    ]
