# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20170922_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='fecha',
            field=models.DateField(help_text='Formato mm/dd/yyyy'),
        ),
    ]
